baseURL: https://malleable.systems/
languageCode: en-gb
title: Malleable Systems Collective
theme: ananke
enableRobotsTXT: true

params:
  description:
    "The Malleable Systems Collective catalogs and experiments with malleable
    software and systems that reset the balance of power in computing"
  custom_css:
    - css/forkawesome/fork-awesome.css
    - css/custom.css
  licenseURL: https://creativecommons.org/licenses/by-sa/4.0/
  licenseName: CC BY-SA 4.0
  logo: /meta/header.svg
  mainSections:
    - blog
  email: mailto:hello@malleable.systems
  newsletter: https://buttondown.email/malleable-systems
  mastodon: https://hachyderm.io/@malleablesys
  twitter: https://twitter.com/malleablesys
  forum: https://forum.malleable.systems
  matrix: https://matrix.to/#/#malleable-systems:matrix.org
  github: https://github.com/malleable-systems
  source: https://github.com/malleable-systems/malleable.systems

social:
  twitter: malleablesys

permalinks:
  blog: /blog/:year/:month/:day/:title/
  tags: /blog/tags/:title/
  categories: /blog/categories/:title/
  pages: /:title/

markup:
  goldmark:
    renderer:
      unsafe: true
